# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
# cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
# Mayor.create(name: 'Emanuel', city: cities.first)


IsoCountry.create(iso_name:"AFGHANISTAN", iso:"AF",iso3:"AFG",name:"Afghanistan",numcode:4);
IsoCountry.create(iso_name:"ALBANIA", iso:"AL",iso3:"ALB",name:"Albania",numcode:8);
IsoCountry.create(iso_name:"ALGERIA", iso:"DZ",iso3:"DZA",name:"Algeria",numcode:12);
IsoCountry.create(iso_name:"AMERICAN SAMOA", iso:"AS",iso3:"ASM",name:"American Samoa",numcode:16);
IsoCountry.create(iso_name:"ANDORRA", iso:"AD",iso3:"AND",name:"Andorra",numcode:20);
IsoCountry.create(iso_name:"ANGOLA", iso:"AO",iso3:"AGO",name:"Angola",numcode:24);
IsoCountry.create(iso_name:"ANGUILLA", iso:"AI",iso3:"AIA",name:"Anguilla",numcode:660);
IsoCountry.create(iso_name:"ANTIGUA AND BARBUDA", iso:"AG",iso3:"ATG",name:"Antigua and Barbuda",numcode:28);
IsoCountry.create(iso_name:"ARGENTINA", iso:"AR",iso3:"ARG",name:"Argentina",numcode:32);
IsoCountry.create(iso_name:"ARMENIA", iso:"AM",iso3:"ARM",name:"Armenia",numcode:51);
IsoCountry.create(iso_name:"ARUBA", iso:"AW",iso3:"ABW",name:"Aruba",numcode:533);
IsoCountry.create(iso_name:"AUSTRALIA", iso:"AU",iso3:"AUS",name:"Australia",numcode:36);
IsoCountry.create(iso_name:"AUSTRIA", iso:"AT",iso3:"AUT",name:"Austria",numcode:40);
IsoCountry.create(iso_name:"AZERBAIJAN", iso:"AZ",iso3:"AZE",name:"Azerbaijan",numcode:31);
IsoCountry.create(iso_name:"BAHAMAS", iso:"BS",iso3:"BHS",name:"Bahamas",numcode:44);
IsoCountry.create(iso_name:"BAHRAIN", iso:"BH",iso3:"BHR",name:"Bahrain",numcode:48);
IsoCountry.create(iso_name:"BANGLADESH", iso:"BD",iso3:"BGD",name:"Bangladesh",numcode:50);
IsoCountry.create(iso_name:"BARBADOS", iso:"BB",iso3:"BRB",name:"Barbados",numcode:52);
IsoCountry.create(iso_name:"BELARUS", iso:"BY",iso3:"BLR",name:"Belarus",numcode:112);
IsoCountry.create(iso_name:"BELGIUM", iso:"BE",iso3:"BEL",name:"Belgium",numcode:56);
IsoCountry.create(iso_name:"BELIZE", iso:"BZ",iso3:"BLZ",name:"Belize",numcode:84);
IsoCountry.create(iso_name:"BENIN", iso:"BJ",iso3:"BEN",name:"Benin",numcode:204);
IsoCountry.create(iso_name:"BERMUDA", iso:"BM",iso3:"BMU",name:"Bermuda",numcode:60);
IsoCountry.create(iso_name:"BHUTAN", iso:"BT",iso3:"BTN",name:"Bhutan",numcode:64);
IsoCountry.create(iso_name:"BOLIVIA", iso:"BO",iso3:"BOL",name:"Bolivia",numcode:68);
IsoCountry.create(iso_name:"BOSNIA AND HERZEGOVINA", iso:"BA",iso3:"BIH",name:"Bosnia and Herzegovina",numcode:70);
IsoCountry.create(iso_name:"BOTSWANA", iso:"BW",iso3:"BWA",name:"Botswana",numcode:72);
IsoCountry.create(iso_name:"BRAZIL", iso:"BR",iso3:"BRA",name:"Brazil",numcode:76);
IsoCountry.create(iso_name:"BRUNEI DARUSSALAM", iso:"BN",iso3:"BRN",name:"Brunei Darussalam",numcode:96);
IsoCountry.create(iso_name:"BULGARIA", iso:"BG",iso3:"BGR",name:"Bulgaria",numcode:100);
IsoCountry.create(iso_name:"BURKINA FASO", iso:"BF",iso3:"BFA",name:"Burkina Faso",numcode:854);
IsoCountry.create(iso_name:"BURUNDI", iso:"BI",iso3:"BDI",name:"Burundi",numcode:108);
IsoCountry.create(iso_name:"CAMBODIA", iso:"KH",iso3:"KHM",name:"Cambodia",numcode:116);
IsoCountry.create(iso_name:"CAMEROON", iso:"CM",iso3:"CMR",name:"Cameroon",numcode:120);
IsoCountry.create(iso_name:"CANADA", iso:"CA",iso3:"CAN",name:"Canada",numcode:124);
IsoCountry.create(iso_name:"CAPE VERDE", iso:"CV",iso3:"CPV",name:"Cape Verde",numcode:132);
IsoCountry.create(iso_name:"CAYMAN ISLANDS", iso:"KY",iso3:"CYM",name:"Cayman Islands",numcode:136);
IsoCountry.create(iso_name:"CENTRAL AFRICAN REPUBLIC", iso:"CF",iso3:"CAF",name:"Central African Republic",numcode:140);
IsoCountry.create(iso_name:"CHAD", iso:"TD",iso3:"TCD",name:"Chad",numcode:148);
IsoCountry.create(iso_name:"CHILE", iso:"CL",iso3:"CHL",name:"Chile",numcode:152);
IsoCountry.create(iso_name:"CHINA", iso:"CN",iso3:"CHN",name:"China",numcode:156);
IsoCountry.create(iso_name:"COLOMBIA", iso:"CO",iso3:"COL",name:"Colombia",numcode:170);
IsoCountry.create(iso_name:"COMOROS", iso:"KM",iso3:"COM",name:"Comoros",numcode:174);
IsoCountry.create(iso_name:"CONGO", iso:"CG",iso3:"COG",name:"Congo",numcode:178);
IsoCountry.create(iso_name:"CONGO, THE DEMOCRATIC REPUBLIC OF THE", iso:"CD",iso3:"COD",name:"Congo, the Democratic Republic of the",numcode:180);
IsoCountry.create(iso_name:"COOK ISLANDS", iso:"CK",iso3:"COK",name:"Cook Islands",numcode:184);
IsoCountry.create(iso_name:"COSTA RICA", iso:"CR",iso3:"CRI",name:"Costa Rica",numcode:188);
IsoCountry.create(iso_name:"COTE D'IVOIRE", iso:"CI",iso3:"CIV",name:"Cote D'Ivoire",numcode:384);
IsoCountry.create(iso_name:"CROATIA", iso:"HR",iso3:"HRV",name:"Croatia",numcode:191);
IsoCountry.create(iso_name:"CUBA", iso:"CU",iso3:"CUB",name:"Cuba",numcode:192);
IsoCountry.create(iso_name:"CYPRUS", iso:"CY",iso3:"CYP",name:"Cyprus",numcode:196);
IsoCountry.create(iso_name:"CZECH REPUBLIC", iso:"CZ",iso3:"CZE",name:"Czech Republic",numcode:203);
IsoCountry.create(iso_name:"DENMARK", iso:"DK",iso3:"DNK",name:"Denmark",numcode:208);
IsoCountry.create(iso_name:"DJIBOUTI", iso:"DJ",iso3:"DJI",name:"Djibouti",numcode:262);
IsoCountry.create(iso_name:"DOMINICA", iso:"DM",iso3:"DMA",name:"Dominica",numcode:212);
IsoCountry.create(iso_name:"DOMINICAN REPUBLIC", iso:"DO",iso3:"DOM",name:"Dominican Republic",numcode:214);
IsoCountry.create(iso_name:"ECUADOR", iso:"EC",iso3:"ECU",name:"Ecuador",numcode:218);
IsoCountry.create(iso_name:"EGYPT", iso:"EG",iso3:"EGY",name:"Egypt",numcode:818);
IsoCountry.create(iso_name:"EL SALVADOR", iso:"SV",iso3:"SLV",name:"El Salvador",numcode:222);
IsoCountry.create(iso_name:"EQUATORIAL GUINEA", iso:"GQ",iso3:"GNQ",name:"Equatorial Guinea",numcode:226);
IsoCountry.create(iso_name:"ERITREA", iso:"ER",iso3:"ERI",name:"Eritrea",numcode:232);
IsoCountry.create(iso_name:"ESTONIA", iso:"EE",iso3:"EST",name:"Estonia",numcode:233);
IsoCountry.create(iso_name:"ETHIOPIA", iso:"ET",iso3:"ETH",name:"Ethiopia",numcode:231);
IsoCountry.create(iso_name:"FALKLAND ISLANDS (MALVINAS)", iso:"FK",iso3:"FLK",name:"Falkland Islands (Malvinas)",numcode:238);
IsoCountry.create(iso_name:"FAROE ISLANDS", iso:"FO",iso3:"FRO",name:"Faroe Islands",numcode:234);
IsoCountry.create(iso_name:"FIJI", iso:"FJ",iso3:"FJI",name:"Fiji",numcode:242);
IsoCountry.create(iso_name:"FINLAND", iso:"FI",iso3:"FIN",name:"Finland",numcode:246);
IsoCountry.create(iso_name:"FRANCE", iso:"FR",iso3:"FRA",name:"France",numcode:250);
IsoCountry.create(iso_name:"FRENCH GUIANA", iso:"GF",iso3:"GUF",name:"French Guiana",numcode:254);
IsoCountry.create(iso_name:"FRENCH POLYNESIA", iso:"PF",iso3:"PYF",name:"French Polynesia",numcode:258);
IsoCountry.create(iso_name:"GABON", iso:"GA",iso3:"GAB",name:"Gabon",numcode:266);
IsoCountry.create(iso_name:"GAMBIA", iso:"GM",iso3:"GMB",name:"Gambia",numcode:270);
IsoCountry.create(iso_name:"GEORGIA", iso:"GE",iso3:"GEO",name:"Georgia",numcode:268);
IsoCountry.create(iso_name:"GERMANY", iso:"DE",iso3:"DEU",name:"Germany",numcode:276);
IsoCountry.create(iso_name:"GHANA", iso:"GH",iso3:"GHA",name:"Ghana",numcode:288);
IsoCountry.create(iso_name:"GIBRALTAR", iso:"GI",iso3:"GIB",name:"Gibraltar",numcode:292);
IsoCountry.create(iso_name:"GREECE", iso:"GR",iso3:"GRC",name:"Greece",numcode:300);
IsoCountry.create(iso_name:"GREENLAND", iso:"GL",iso3:"GRL",name:"Greenland",numcode:304);
IsoCountry.create(iso_name:"GRENADA", iso:"GD",iso3:"GRD",name:"Grenada",numcode:308);
IsoCountry.create(iso_name:"GUADELOUPE", iso:"GP",iso3:"GLP",name:"Guadeloupe",numcode:312);
IsoCountry.create(iso_name:"GUAM", iso:"GU",iso3:"GUM",name:"Guam",numcode:316);
IsoCountry.create(iso_name:"GUATEMALA", iso:"GT",iso3:"GTM",name:"Guatemala",numcode:320);
IsoCountry.create(iso_name:"GUINEA", iso:"GN",iso3:"GIN",name:"Guinea",numcode:324);
IsoCountry.create(iso_name:"GUINEA-BISSAU", iso:"GW",iso3:"GNB",name:"Guinea-Bissau",numcode:624);
IsoCountry.create(iso_name:"GUYANA", iso:"GY",iso3:"GUY",name:"Guyana",numcode:328);
IsoCountry.create(iso_name:"HAITI", iso:"HT",iso3:"HTI",name:"Haiti",numcode:332);
IsoCountry.create(iso_name:"HOLY SEE (VATICAN CITY STATE)", iso:"VA",iso3:"VAT",name:"Holy See (Vatican City State)",numcode:336);
IsoCountry.create(iso_name:"HONDURAS", iso:"HN",iso3:"HND",name:"Honduras",numcode:340);
IsoCountry.create(iso_name:"HONG KONG", iso:"HK",iso3:"HKG",name:"Hong Kong",numcode:344);
IsoCountry.create(iso_name:"HUNGARY", iso:"HU",iso3:"HUN",name:"Hungary",numcode:348);
IsoCountry.create(iso_name:"ICELAND", iso:"IS",iso3:"ISL",name:"Iceland",numcode:352);
IsoCountry.create(iso_name:"INDIA", iso:"IN",iso3:"IND",name:"India",numcode:356);
IsoCountry.create(iso_name:"INDONESIA", iso:"ID",iso3:"IDN",name:"Indonesia",numcode:360);
IsoCountry.create(iso_name:"IRAN, ISLAMIC REPUBLIC OF", iso:"IR",iso3:"IRN",name:"Iran, Islamic Republic of",numcode:364);
IsoCountry.create(iso_name:"IRAQ", iso:"IQ",iso3:"IRQ",name:"Iraq",numcode:368);
IsoCountry.create(iso_name:"IRELAND", iso:"IE",iso3:"IRL",name:"Ireland",numcode:372);
IsoCountry.create(iso_name:"ISRAEL", iso:"IL",iso3:"ISR",name:"Israel",numcode:376);
IsoCountry.create(iso_name:"ITALY", iso:"IT",iso3:"ITA",name:"Italy",numcode:380);
IsoCountry.create(iso_name:"JAMAICA", iso:"JM",iso3:"JAM",name:"Jamaica",numcode:388);
IsoCountry.create(iso_name:"JAPAN", iso:"JP",iso3:"JPN",name:"Japan",numcode:392);
IsoCountry.create(iso_name:"JORDAN", iso:"JO",iso3:"JOR",name:"Jordan",numcode:400);
IsoCountry.create(iso_name:"KAZAKHSTAN", iso:"KZ",iso3:"KAZ",name:"Kazakhstan",numcode:398);
IsoCountry.create(iso_name:"KENYA", iso:"KE",iso3:"KEN",name:"Kenya",numcode:404);
IsoCountry.create(iso_name:"KIRIBATI", iso:"KI",iso3:"KIR",name:"Kiribati",numcode:296);
IsoCountry.create(iso_name:"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", iso:"KP",iso3:"PRK",name:"North Korea",numcode:408);
IsoCountry.create(iso_name:"KOREA, REPUBLIC OF", iso:"KR",iso3:"KOR",name:"South Korea",numcode:410);
IsoCountry.create(iso_name:"KUWAIT", iso:"KW",iso3:"KWT",name:"Kuwait",numcode:414);
IsoCountry.create(iso_name:"KYRGYZSTAN", iso:"KG",iso3:"KGZ",name:"Kyrgyzstan",numcode:417);
IsoCountry.create(iso_name:"LAO PEOPLE'S DEMOCRATIC REPUBLIC", iso:"LA",iso3:"LAO",name:"Lao People's Democratic Republic",numcode:418);
IsoCountry.create(iso_name:"LATVIA", iso:"LV",iso3:"LVA",name:"Latvia",numcode:428);
IsoCountry.create(iso_name:"LEBANON", iso:"LB",iso3:"LBN",name:"Lebanon",numcode:422);
IsoCountry.create(iso_name:"LESOTHO", iso:"LS",iso3:"LSO",name:"Lesotho",numcode:426);
IsoCountry.create(iso_name:"LIBERIA", iso:"LR",iso3:"LBR",name:"Liberia",numcode:430);
IsoCountry.create(iso_name:"LIBYAN ARAB JAMAHIRIYA", iso:"LY",iso3:"LBY",name:"Libyan Arab Jamahiriya",numcode:434);
IsoCountry.create(iso_name:"LIECHTENSTEIN", iso:"LI",iso3:"LIE",name:"Liechtenstein",numcode:438);
IsoCountry.create(iso_name:"LITHUANIA", iso:"LT",iso3:"LTU",name:"Lithuania",numcode:440);
IsoCountry.create(iso_name:"LUXEMBOURG", iso:"LU",iso3:"LUX",name:"Luxembourg",numcode:442);
IsoCountry.create(iso_name:"MACAO", iso:"MO",iso3:"MAC",name:"Macao",numcode:446);
IsoCountry.create(iso_name:"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", iso:"MK",iso3:"MKD",name:"Macedonia",numcode:807);
IsoCountry.create(iso_name:"MADAGASCAR", iso:"MG",iso3:"MDG",name:"Madagascar",numcode:450);
IsoCountry.create(iso_name:"MALAWI", iso:"MW",iso3:"MWI",name:"Malawi",numcode:454);
IsoCountry.create(iso_name:"MALAYSIA", iso:"MY",iso3:"MYS",name:"Malaysia",numcode:458);
IsoCountry.create(iso_name:"MALDIVES", iso:"MV",iso3:"MDV",name:"Maldives",numcode:462);
IsoCountry.create(iso_name:"MALI", iso:"ML",iso3:"MLI",name:"Mali",numcode:466);
IsoCountry.create(iso_name:"MALTA", iso:"MT",iso3:"MLT",name:"Malta",numcode:470);
IsoCountry.create(iso_name:"MARSHALL ISLANDS", iso:"MH",iso3:"MHL",name:"Marshall Islands",numcode:584);
IsoCountry.create(iso_name:"MARTINIQUE", iso:"MQ",iso3:"MTQ",name:"Martinique",numcode:474);
IsoCountry.create(iso_name:"MAURITANIA", iso:"MR",iso3:"MRT",name:"Mauritania",numcode:478);
IsoCountry.create(iso_name:"MAURITIUS", iso:"MU",iso3:"MUS",name:"Mauritius",numcode:480);
IsoCountry.create(iso_name:"MEXICO", iso:"MX",iso3:"MEX",name:"Mexico",numcode:484);
IsoCountry.create(iso_name:"MICRONESIA, FEDERATED STATES OF", iso:"FM",iso3:"FSM",name:"Micronesia, Federated States of",numcode:583);
IsoCountry.create(iso_name:"MOLDOVA, REPUBLIC OF", iso:"MD",iso3:"MDA",name:"Moldova, Republic of",numcode:498);
IsoCountry.create(iso_name:"MONACO", iso:"MC",iso3:"MCO",name:"Monaco",numcode:492);
IsoCountry.create(iso_name:"MONGOLIA", iso:"MN",iso3:"MNG",name:"Mongolia",numcode:496);
IsoCountry.create(iso_name:"MONTSERRAT", iso:"MS",iso3:"MSR",name:"Montserrat",numcode:500);
IsoCountry.create(iso_name:"MOROCCO", iso:"MA",iso3:"MAR",name:"Morocco",numcode:504);
IsoCountry.create(iso_name:"MOZAMBIQUE", iso:"MZ",iso3:"MOZ",name:"Mozambique",numcode:508);
IsoCountry.create(iso_name:"MYANMAR", iso:"MM",iso3:"MMR",name:"Myanmar",numcode:104);
IsoCountry.create(iso_name:"NAMIBIA", iso:"NA",iso3:"NAM",name:"Namibia",numcode:516);
IsoCountry.create(iso_name:"NAURU", iso:"NR",iso3:"NRU",name:"Nauru",numcode:520);
IsoCountry.create(iso_name:"NEPAL", iso:"NP",iso3:"NPL",name:"Nepal",numcode:524);
IsoCountry.create(iso_name:"NETHERLANDS", iso:"NL",iso3:"NLD",name:"Netherlands",numcode:528);
IsoCountry.create(iso_name:"NETHERLANDS ANTILLES", iso:"AN",iso3:"ANT",name:"Netherlands Antilles",numcode:530);
IsoCountry.create(iso_name:"NEW CALEDONIA", iso:"NC",iso3:"NCL",name:"New Caledonia",numcode:540);
IsoCountry.create(iso_name:"NEW ZEALAND", iso:"NZ",iso3:"NZL",name:"New Zealand",numcode:554);
IsoCountry.create(iso_name:"NICARAGUA", iso:"NI",iso3:"NIC",name:"Nicaragua",numcode:558);
IsoCountry.create(iso_name:"NIGER", iso:"NE",iso3:"NER",name:"Niger",numcode:562);
IsoCountry.create(iso_name:"NIGERIA", iso:"NG",iso3:"NGA",name:"Nigeria",numcode:566);
IsoCountry.create(iso_name:"NIUE", iso:"NU",iso3:"NIU",name:"Niue",numcode:570);
IsoCountry.create(iso_name:"NORFOLK ISLAND", iso:"NF",iso3:"NFK",name:"Norfolk Island",numcode:574);
IsoCountry.create(iso_name:"NORTHERN MARIANA ISLANDS", iso:"MP",iso3:"MNP",name:"Northern Mariana Islands",numcode:580);
IsoCountry.create(iso_name:"NORWAY", iso:"NO",iso3:"NOR",name:"Norway",numcode:578);
IsoCountry.create(iso_name:"OMAN", iso:"OM",iso3:"OMN",name:"Oman",numcode:512);
IsoCountry.create(iso_name:"PAKISTAN", iso:"PK",iso3:"PAK",name:"Pakistan",numcode:586);
IsoCountry.create(iso_name:"PALAU", iso:"PW",iso3:"PLW",name:"Palau",numcode:585);
IsoCountry.create(iso_name:"PANAMA", iso:"PA",iso3:"PAN",name:"Panama",numcode:591);
IsoCountry.create(iso_name:"PAPUA NEW GUINEA", iso:"PG",iso3:"PNG",name:"Papua New Guinea",numcode:598);
IsoCountry.create(iso_name:"PARAGUAY", iso:"PY",iso3:"PRY",name:"Paraguay",numcode:600);
IsoCountry.create(iso_name:"PERU", iso:"PE",iso3:"PER",name:"Peru",numcode:604);
IsoCountry.create(iso_name:"PHILIPPINES", iso:"PH",iso3:"PHL",name:"Philippines",numcode:608);
IsoCountry.create(iso_name:"PITCAIRN", iso:"PN",iso3:"PCN",name:"Pitcairn",numcode:612);
IsoCountry.create(iso_name:"POLAND", iso:"PL",iso3:"POL",name:"Poland",numcode:616);
IsoCountry.create(iso_name:"PORTUGAL", iso:"PT",iso3:"PRT",name:"Portugal",numcode:620);
IsoCountry.create(iso_name:"PUERTO RICO", iso:"PR",iso3:"PRI",name:"Puerto Rico",numcode:630);
IsoCountry.create(iso_name:"QATAR", iso:"QA",iso3:"QAT",name:"Qatar",numcode:634);
IsoCountry.create(iso_name:"REUNION", iso:"RE",iso3:"REU",name:"Reunion",numcode:638);
IsoCountry.create(iso_name:"ROMANIA", iso:"RO",iso3:"ROM",name:"Romania",numcode:642);
IsoCountry.create(iso_name:"RUSSIAN FEDERATION", iso:"RU",iso3:"RUS",name:"Russian Federation",numcode:643);
IsoCountry.create(iso_name:"RWANDA", iso:"RW",iso3:"RWA",name:"Rwanda",numcode:646);
IsoCountry.create(iso_name:"SAINT HELENA", iso:"SH",iso3:"SHN",name:"Saint Helena",numcode:654);
IsoCountry.create(iso_name:"SAINT KITTS AND NEVIS", iso:"KN",iso3:"KNA",name:"Saint Kitts and Nevis",numcode:659);
IsoCountry.create(iso_name:"SAINT LUCIA", iso:"LC",iso3:"LCA",name:"Saint Lucia",numcode:662);
IsoCountry.create(iso_name:"SAINT PIERRE AND MIQUELON", iso:"PM",iso3:"SPM",name:"Saint Pierre and Miquelon",numcode:666);
IsoCountry.create(iso_name:"SAINT VINCENT AND THE GRENADINES", iso:"VC",iso3:"VCT",name:"Saint Vincent and the Grenadines",numcode:670);
IsoCountry.create(iso_name:"SAMOA", iso:"WS",iso3:"WSM",name:"Samoa",numcode:882);
IsoCountry.create(iso_name:"SAN MARINO", iso:"SM",iso3:"SMR",name:"San Marino",numcode:674);
IsoCountry.create(iso_name:"SAO TOME AND PRINCIPE", iso:"ST",iso3:"STP",name:"Sao Tome and Principe",numcode:678);
IsoCountry.create(iso_name:"SAUDI ARABIA", iso:"SA",iso3:"SAU",name:"Saudi Arabia",numcode:682);
IsoCountry.create(iso_name:"SENEGAL", iso:"SN",iso3:"SEN",name:"Senegal",numcode:686);
IsoCountry.create(iso_name:"SEYCHELLES", iso:"SC",iso3:"SYC",name:"Seychelles",numcode:690);
IsoCountry.create(iso_name:"SIERRA LEONE", iso:"SL",iso3:"SLE",name:"Sierra Leone",numcode:694);
IsoCountry.create(iso_name:"SINGAPORE", iso:"SG",iso3:"SGP",name:"Singapore",numcode:702);
IsoCountry.create(iso_name:"SLOVAKIA", iso:"SK",iso3:"SVK",name:"Slovakia",numcode:703);
IsoCountry.create(iso_name:"SLOVENIA", iso:"SI",iso3:"SVN",name:"Slovenia",numcode:705);
IsoCountry.create(iso_name:"SOLOMON ISLANDS", iso:"SB",iso3:"SLB",name:"Solomon Islands",numcode:90);
IsoCountry.create(iso_name:"SOMALIA", iso:"SO",iso3:"SOM",name:"Somalia",numcode:706);
IsoCountry.create(iso_name:"SOUTH AFRICA", iso:"ZA",iso3:"ZAF",name:"South Africa",numcode:710);
IsoCountry.create(iso_name:"SPAIN", iso:"ES",iso3:"ESP",name:"Spain",numcode:724);
IsoCountry.create(iso_name:"SRI LANKA", iso:"LK",iso3:"LKA",name:"Sri Lanka",numcode:144);
IsoCountry.create(iso_name:"SUDAN", iso:"SD",iso3:"SDN",name:"Sudan",numcode:736);
IsoCountry.create(iso_name:"SURINAME", iso:"SR",iso3:"SUR",name:"Suriname",numcode:740);
IsoCountry.create(iso_name:"SVALBARD AND JAN MAYEN", iso:"SJ",iso3:"SJM",name:"Svalbard and Jan Mayen",numcode:744);
IsoCountry.create(iso_name:"SWAZILAND", iso:"SZ",iso3:"SWZ",name:"Swaziland",numcode:748);
IsoCountry.create(iso_name:"SWEDEN", iso:"SE",iso3:"SWE",name:"Sweden",numcode:752);
IsoCountry.create(iso_name:"SWITZERLAND", iso:"CH",iso3:"CHE",name:"Switzerland",numcode:756);
IsoCountry.create(iso_name:"SYRIAN ARAB REPUBLIC", iso:"SY",iso3:"SYR",name:"Syrian Arab Republic",numcode:760);
IsoCountry.create(iso_name:"TAIWAN, PROVINCE OF CHINA", iso:"TW",iso3:"TWN",name:"Taiwan",numcode:158);
IsoCountry.create(iso_name:"TAJIKISTAN", iso:"TJ",iso3:"TJK",name:"Tajikistan",numcode:762);
IsoCountry.create(iso_name:"TANZANIA, UNITED REPUBLIC OF", iso:"TZ",iso3:"TZA",name:"Tanzania, United Republic of",numcode:834);
IsoCountry.create(iso_name:"THAILAND", iso:"TH",iso3:"THA",name:"Thailand",numcode:764);
IsoCountry.create(iso_name:"TOGO", iso:"TG",iso3:"TGO",name:"Togo",numcode:768);
IsoCountry.create(iso_name:"TOKELAU", iso:"TK",iso3:"TKL",name:"Tokelau",numcode:772);
IsoCountry.create(iso_name:"TONGA", iso:"TO",iso3:"TON",name:"Tonga",numcode:776);
IsoCountry.create(iso_name:"TRINIDAD AND TOBAGO", iso:"TT",iso3:"TTO",name:"Trinidad and Tobago",numcode:780);
IsoCountry.create(iso_name:"TUNISIA", iso:"TN",iso3:"TUN",name:"Tunisia",numcode:788);
IsoCountry.create(iso_name:"TURKEY", iso:"TR",iso3:"TUR",name:"Turkey",numcode:792);
IsoCountry.create(iso_name:"TURKMENISTAN", iso:"TM",iso3:"TKM",name:"Turkmenistan",numcode:795);
IsoCountry.create(iso_name:"TURKS AND CAICOS ISLANDS", iso:"TC",iso3:"TCA",name:"Turks and Caicos Islands",numcode:796);
IsoCountry.create(iso_name:"TUVALU", iso:"TV",iso3:"TUV",name:"Tuvalu",numcode:798);
IsoCountry.create(iso_name:"UGANDA", iso:"UG",iso3:"UGA",name:"Uganda",numcode:800);
IsoCountry.create(iso_name:"UKRAINE", iso:"UA",iso3:"UKR",name:"Ukraine",numcode:804);
IsoCountry.create(iso_name:"UNITED ARAB EMIRATES", iso:"AE",iso3:"ARE",name:"United Arab Emirates",numcode:784);
IsoCountry.create(iso_name:"UNITED KINGDOM", iso:"GB",iso3:"GBR",name:"United Kingdom",numcode:826);
IsoCountry.create(iso_name:"UNITED STATES", iso:"US",iso3:"USA",name:"United States",numcode:840);
IsoCountry.create(iso_name:"URUGUAY", iso:"UY",iso3:"URY",name:"Uruguay",numcode:858);
IsoCountry.create(iso_name:"UZBEKISTAN", iso:"UZ",iso3:"UZB",name:"Uzbekistan",numcode:860);
IsoCountry.create(iso_name:"VANUATU", iso:"VU",iso3:"VUT",name:"Vanuatu",numcode:548);
IsoCountry.create(iso_name:"VENEZUELA", iso:"VE",iso3:"VEN",name:"Venezuela",numcode:862);
IsoCountry.create(iso_name:"VIET NAM", iso:"VN",iso3:"VNM",name:"Viet Nam",numcode:704);
IsoCountry.create(iso_name:"VIRGIN ISLANDS, BRITISH", iso:"VG",iso3:"VGB",name:"Virgin Islands, British",numcode:92);
IsoCountry.create(iso_name:"VIRGIN ISLANDS, U.S.", iso:"VI",iso3:"VIR",name:"Virgin Islands, U.S.",numcode:850);
IsoCountry.create(iso_name:"WALLIS AND FUTUNA", iso:"WF",iso3:"WLF",name:"Wallis and Futuna",numcode:876);
IsoCountry.create(iso_name:"WESTERN SAHARA", iso:"EH",iso3:"ESH",name:"Western Sahara",numcode:732);
IsoCountry.create(iso_name:"YEMEN", iso:"YE",iso3:"YEM",name:"Yemen",numcode:887);
IsoCountry.create(iso_name:"ZAMBIA", iso:"ZM",iso3:"ZMB",name:"Zambia",numcode:894);
IsoCountry.create(iso_name:"ZIMBABWE", iso:"ZW",iso3:"ZWE",name:"Zimbabwe",numcode:716);
IsoCountry.create(iso_name:"", iso:"",iso3:"",name:"Others",numcode:99999);